/**
 * DISCLAIMER
 * <p>
 * This java code consisting in java enumerations, hereafter <b>The Code</b>, has been prepared by <b>St&eacute;phane Coutant</b>, 
 * hereafter <b>The Author</b> who is the owner of <b>The Code</b> therein.
 * <p>
 * Permission is hereby granted to use <b>The Code</b> for both private and commercial usage, subject to the following conditions: 
 * <ul>
 * 	<li>(i) that <b>The Author</b> shall not have any responsibility or liability whatsoever to any other party from the use or 
 * publication of <b>The Code</b>;
 * 	<li>(ii) that one cannot rely on the accuracy or finality of <b>The Code</b>; 
 * 	<li>(iii) that the willingness of <b>The Author</b> to provide the <b>The Code</b> does not in any way convey or imply any 
 * responsibility for any product or service using <b>The Code</b> and <b>The Author</b> specifically disclaims any such responsibility 
 * to any party;
 *  <li>and (iv) that <b>The Code</b> package domain name <code>org.iso4j</code> refers to a fake domain created for the need of publication 
 *  of <b>The Code>/b> on public repository and should not be used as is (the user of <b>The Code</b> should rather copy the content in 
 *  own project with own package naming policy). In any case, <b>The Author</b> disclaims any responsibility in case this domain name 
 *  enters or may enter in collision with any registered domain, past or future.
 * </ul> 
 * <p>
 * Implementation of <b>The Code</b> may require licenses under third party intellectual property rights, including without limitation, 
 * patent rights. <b>The Author</b> is not, and shall not be held responsible in any manner for identifying or failing to identify any 
 * or all such third party intellectual property rights.
 * <p>
 * <b>The Code</b> is provided "AS IS", "WHERE IS" and "WITH ALL FAULTS", and <b>The Author</b> makes any warranty of any kind, 
 * express or implied, including any implied warranties of merchantability, non-infringement of third party intellectual property rights 
 * (whether or not <b>The Author</b> has been advised, has reason to know, or is otherwise in fact aware of any information), 
 * and fitness for a particular purpose (including any errors and omissions in <b>The Code</b>).
 * <p>
 * To the extent permitted by applicable law, <b>The Author</b> shall not be liable to any user of <b>The Code</b> for any damages 
 * (other than direct actual out-of-pocket damages) under any theory of law, including, without limitation, any special, consequential, 
 * incidental, or punitive damages, nor any damages for loss of business profits, business interruption, loss of business information, or
 * other monetary loss, nor any damages arising out of third party claims (including claims of intellectual property infringement) 
 * arising out of the use of or inability to use <b>The Code</b>, even if advised of the possibility of such damages.
 * <p>
 * <b>The Code</b>, including technical data, may be subject to export or import regulations in different countries.
 * Any user of <b>The Code</b> agrees to comply strictly with all such regulations and acknowledges that it has the
 * responsibility to obtain licenses to export, re-export, or import <b>The Code</b>.
 * <p>
 */

//package org.iso4j;
package org.iso4j;

/**
 * <code>ILanguages</code> is an interface wrapping the ISO 639 language codes norm as a java enumeration with access methods to various
 * information pertaining to a language, such as local language names in various languages.
 * <p>
 * Input source (R) [fr|es|en].wikipedia.org/wiki/ISO_639_1 and unicode from https://www.branah.com/unicode-converter.  
 * <p>
 * @author St&eacute;phane Coutant (fra)
 */

public interface ILanguages {

	/** The standard ISO 639-2 language codes. */
	public enum Iso639LanguageCode {
		
		// SYNTAX
		// Alpha-3(Alpha-2, Original Language Name, English name, Unicode)
		// NOTE
		// - Some alpha-3 language codes do not have alpha-2 code (hence null)
		// - General purpose language codes do not have original language name (hence null)
		// - If unicode is null, getUnicode() will convert Latin original language name in UTF16-BE
		// - qaa-qtz range are valid codes reserved for local use: they are listed here in extenso
		//   (to avoid exception when static valueOf(String) is used to get an instance of this enumeration; note that valueOf cannot be overridden)
		
		aar ("aa", "Afaraf", "Afar", null),
		abk ("ab", "�?ҧ�?уа", "Abkhaz", "\u0410\u04a7\u0441\u0443\u0430"),
		ace (null, "Acehnese", "Achinese", null),
		ach (null, "Acoli", "Acoli", null),
		ada (null, "adangbɛ", "Adangme", "\u0061\u0064\u0061\u006e\u0067\u0062\u025b"),
		ady (null, "адыг�?бз�?, адыгабз�?", "Adyghe, Adygei", "\u0430\u0434\u044b\u0433\u044d\u0431\u0437\u044d, \u0430\u0434\u044b\u0433\u0430\u0431\u0437\u044d"),
		afa (null, null, "Afro-Asiatic languages", null),
		afh (null, "Afrihili", "Afrihili", null),
		afr ("af", "Afrikaans", "Afrikaans", null),
		ain (null, "アイヌ イタㇰ (イタッㇰ)", "Ainu", "\u30a2\u30a4\u30cc \u30a4\u30bf\u31f0\u0028\u30a4\u30bf\u30c3\u31f0\u0029"), // Ainu chars do not render
		aka ("ak", "Akan", "Akan", null),
		akk (null, "Akkadû, liš�?num akkadītum", "Akkadian", "\u0041\u006b\u006b\u0061\u0064\u00fb\u002c \u006c\u0069\u0161\u0101\u006e\u0075\u006d \u0061\u006b\u006b\u0061\u0064\u012b\u0074\u0075\u006d"),
		alb ("sq", "Shqip", "Albanian", null),
		ale (null, "Aléoute", "Aleut", "\u0041\u006c\u00e9\u006f\u0075\u0074\u0065"),
		alg (null, null, "Algonquian languages", null),
		alt (null, "алтай тили", "Southern Altai", "\u0430\u043b\u0442\u0430\u0439 \u0442\u0438\u043b\u0438"),
		amh ("am", "አማርኛ", "Amharic", "\u12a0\u121b\u122d\u129b"),
		ang (null, "Englisc", "English, Old  (ca. 450–1100)", null),
		anp (null, "Angika", "Angika", null),
		apa (null, null, "Apache languages", null),
		ara ("ar", "العربية", "Arabic", "\u0627\u0644\u0639\u0631\u0628\u064a\u0629"),
		arc (null, "�?ܪܡ�?�?", "Official Aramaic, Imperial Aramaic  (700-300 BCE)", "\u0710\u072a\u0721\u071d\u0710"),
		arg ("an", "Aragonés", "Aragonese", "\u0041\u0072\u0061\u0067\u006f\u006e\u00e9\u0073"),
		arm ("hy", "Հայերեն լեզու (arm)", "Armenian", "\u0540\u0561\u0575\u0565\u0580\u0565\u0576 \u056c\u0565\u0566\u0578\u0582"),
		arn (null, "Mapudungun, mapuchedungun", "Mapudungun, Mapuche", null),
		arp (null, "Hinóno'eitíít", "Arapaho", "\u0048\u0069\u006e\u00f3\u006e\u006f\u0027\u0065\u0069\u0074\u00ed\u00ed\u0074"),
		art (null, null, "Artificial languages", null),
		arw (null, "Arawak", "Arawak", null),
		asm ("as", "অসমীয়া", "Assamese", "\u0985\u09b8\u09ae\u09c0\u09af\u09bc\u09be"),
		ast (null, "Asturianu", "Asturian, Bable, Leonese, Asturleonese", null),
		ath (null, "Athapascanes", "Athapascan languages", null),
		aus (null, null, "Australian languages", null),
		ava ("av", "авар мацӀ, магӀарул мацӀ", "Avaric", "\u0430\u0432\u0430\u0440 \u043c\u0430\u0446\u04c0\u002c \u043c\u0430\u0433\u04c0\u0430\u0440\u0443\u043b \u043c\u0430\u0446\u04c0"),
		ave ("ae", "Avesta", "Avestan", null),
		awa (null, "अवधी", "Awadhi", "\u0905\u0935\u0927\u0940"),
		aym ("ay", "Aymar aru", "Aymara", null),
		aze ("az", "Azərbaycanca", "Azerbaijani", null),

		bad (null, null, "Banda languages", null),
		bai (null, "Bamileké", "Bamileke languages", "\u0042\u0061\u006d\u0069\u006c\u0065\u006b\u00e9"),
		bak ("ba", "башҡорт теле", "Bashkir", "\u0431\u0430\u0448\u04a1\u043e\u0440\u0442 \u0442\u0435\u043b\u0435"),
		bal (null, "بلوچی", "Baluchi", "\u0628\u0644\u0648\u0686\u06cc"),
		bam ("bm", "Bamanankan", "Bambara", null),
		ban (null, "Basa Bali", "Balinese", null),
		baq ("eu", "Euskara", "Basque", null),
		bas (null, "ɓasaá", "Basa", "\u0253\u0061\u0073\u0061\u00e1"),
		bat (null, null, "Baltic languages", null),
		bej (null, "بداوية", "Beja, Bedawiyet", "\u0628\u062f\u0627\u0648\u064a\u0629"),
		bel ("be", "Белару�?ка�? мова", "Belarusian", "\u0411\u0435\u043b\u0430\u0440\u0443\u0441\u043a\u0430\u044f \u043c\u043e\u0432\u0430"),
		bem (null, "IchiBemba", "Bemba", null),
		ben ("bn", "বাংলা", "Bengali", "\u09ac\u09be\u0982\u09b2\u09be"),
		ber (null, null, "Berber languages", null),
		bho (null, "भोजप�?री", "Bhojpuri", "\u092d\u094b\u091c\u092a\u0941\u0930\u0940"),
		bih ("bh", "Bihari", "Bihari  (languages)", null),
		bik (null, "Bikol", "Bikol", null),
		bin (null, "Edo", "Bini, Edo", null),
		bis ("bi", "Bislama", "Bislama", null),
		bla (null, "Siksiká, ᓱᖽ�?�ᖿ ", "Siksika", "\u0053\u0069\u006b\u0073\u0069\u006b\u00e1\u002c \u14f1\u15bd\u1427\u15bf"),
		bnt (null, null, "Bantu languages", null),
		bod ("bo", "བོད་ཡིག", "Tibetan", "\u0f56\u0f7c\u0f51\u0f0b\u0f61\u0f72\u0f42"),
		bos ("bs", "Bosanski jezik", "Bosnian", null),
		bra (null, "ब�?रज भाषा, Brij Bhasha", "Braj Basha", "\u092c\u094d\u0930\u091c \u092d\u093e\u0937\u093e\u002c \u0042\u0072\u0069\u006a \u0042\u0068\u0061\u0073\u0068\u0061"),
		bre ("br", "Brezhoneg", "Breton", null),
		btk (null, null, "Batak languages", null),
		bua (null, "бур�?ад х�?л�?н", "Buriat", "\u0431\u0443\u0440\u044f\u0430\u0434 \u0445\u044d\u043b\u044d\u043d"),
		bug (null, "ᨅᨔ ᨕᨘ�?ᨗ", "Buginese", "\u1a05\u1a14 \u1a15\u1a18\u1a01\u1a17"),
		bul ("bg", "българ�?ки език", "Bulgarian", "\u0431\u044a\u043b\u0433\u0430\u0440\u0441\u043a\u0438 \u0435\u0437\u0438\u043a"),
		bur ("my", "မျန္မာစာ", "Burmese", "\u1019\u103b\u1014\u1039\u1019\u102c\u1005\u102c"),
		byn (null, "ብሊና", "Blin, Bilin", "\u1265\u120a\u1293"), 

		cad (null, "Hasí:nay", "Caddo", "\u0048\u0061\u0073\u00ed\u003a\u006e\u0061\u0079"),
		cai (null, null, "Central American Indian languages", null),
		car (null, "Karib", "Galibi Carib", null),
		cat ("ca", "Català", "Catalan", "\u0043\u0061\u0074\u0061\u006c\u00e0"),
		cau (null, null, "Caucasian languages", null),
		ceb (null, "Sinugboanon", "Cebuano", null),
		cel (null, null, "Celtic languages", null),
		ces ("cs", "�?esky, �?eština", "Czech", "\u010d\u0065\u0073\u006b\u0079\u002c \u010d\u0065\u0161\u0074\u0069\u006e\u0061"),
		cha ("ch", "Chamoru", "Chamorro", null),
		chb (null, "Chibcha", "Chibcha", null),
		che ("ce", "нохчийн мотт", "Chechen", "\u043d\u043e\u0445\u0447\u0438\u0439\u043d \u043c\u043e\u0442\u0442"), 
		chg (null, "جغتای", "Chagatai", "\u062c\u063a\u062a\u0627\u06cc"),
		chi ("zh", "中文", "Chinese", "\u4e2d\u6587"), // chinese chars do not render
		chk (null, "Chuuk", "Chuukese", null),
		chm (null, "марий йылме", "Mari", "\u043c\u0430\u0440\u0438\u0439 \u0439\u044b\u043b\u043c\u0435"),
		chn (null, "Chinook", "Chinook jargon", null),
		cho (null, "Chahta Anumpa", "Choctaw", null),
		chp (null, "Dëne Sųłiné, ᑌᓀᓲᒢᕄᓀ", "Chipewyan, Dene Suline", "\u0044\u00eb\u006e\u0065 \u0053\u0173\u0142\u0069\u006e\u00e9\u002c \u144c\u14c0\u14f2\u14a2\u1544\u14c0"),
		chr (null, "�?�ᎳᎩ", "Cherokee", "\u13e3\u13b3\u13a9"),
		chu ("cu", "ѩзыкъ �?ловѣнь�?къ", "Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic", "\u0469\u0437\u044b\u043a\u044a \u0441\u043b\u043e\u0432\u0463\u043d\u044c\u0441\u043a\u044a"),
		chv ("cv", "чӑваш чӗлхи", "Chuvash", "\u0447\u04d1\u0432\u0430\u0448 \u0447\u04d7\u043b\u0445\u0438"),
		chy (null, "Tsêhést", "Cheyenne", "\u0054\u0073\u00ea\u0068\u00e9\u0073\u0074"),
		cmc (null, null, "Chamic languages", null),
		cop (null, "ⲙⲉⲧⲛ̀ⲣⲉⲙⲛ̀ⲭ�?ⲙⲓ", "Coptic", "\u2c99\u2c89\u2ca7\u2c9b\u0300\u2ca3\u2c89\u2c99\u2c9b\u0300\u2cad\u2c8f\u2c99\u2c93"),
		cor ("kw", "Kernewek", "Cornish", null),
		cos ("co", "Corsu, lingua corsa", "Corsican", null),
		cpe (null, null, "creoles and pidgins, English-based", null),
		cpf (null, null, "creoles and pidgins, French-based", null),
		cpp (null, null, "creoles and pidgins, Portuguese-based", null),
		cre ("cr", "ᓀ�?��?�ᔭ�??�??�?�", "Cree", "\u14c0\u1426\u1403\u152d\u140d\u140f\u1423"),
		crh (null, "Qırımtatar tili, къырымтатар тили", "Crimean Tatar, Crimean Turkish", "\u0071\u0131\u0072\u0131\u006d\u0074\u0061\u0074\u0061\u0072 \u0074\u0069\u006c\u0069\u002c \u043a\u044a\u044b\u0440\u044b\u043c\u0442\u0430\u0442\u0430\u0440 \u0442\u0438\u043b\u0438"),
		crp (null, null, "creoles and pidgins", null),
		csb (null, "Kaszëbsczi jãzëk", "Kashubian", "\u006b\u0061\u0073\u007a\u00eb\u0062\u0073\u0063\u007a\u0069 \u006a\u00e3\u007a\u00eb\u006b"),
		cus (null, null, "Cushitic languages", null),
		cym ("cy", "Cymraeg", "Welsh", null),
		cze ("cs", "�?esky, �?eština", "Czech", "\u010d\u0065\u0073\u006b\u0079\u002c \u010d\u0065\u0161\u0074\u0069\u006e\u0061"),

		dak (null, "Lakhota", "Dakota", null),
		dan ("da", "Dansk", "Danish", null),
		dar (null, "дарган мез", "Dargwa", "\u0434\u0430\u0440\u0433\u0430\u043d \u043c\u0435\u0437"),
		day (null, null, "Land Dayak languages", null),
		del (null, "Lënape", "Delaware", "\u004c\u00eb\u006e\u0061\u0070\u0065"),
		den (null, "Slavey", "Slavey", null),
		deu ("de", "Deutsch", "German", null),
		dgr (null, "Tłįchǫ", "Dogrib", "\u0054\u0142\u012f\u0063\u0068\u01eb"),
		din (null, "Thuɔŋjäŋ", "Dinka", "\u0054\u0068\u0075\u0254\u014b\u006a\u00e4\u014b"),
		div ("dv", "ދިވެހިބަ�?", "Divehi, Dhivehi, Maldivian", "\u078b\u07a8\u0788\u07ac\u0780\u07a8\u0784\u07a6\u0790"),
		doi (null, "डोगरी", "Dogri", "\u0921\u094b\u0917\u0930\u0940"),
		dra (null, null, "Dravidian languages", null),
		dsb (null, "Dolnoserbski", "Lower Sorbian", null),
		dua (null, "Douala", "Duala", null),
		dum (null, null, "Dutch, Middle  (ca. 1050–1350)", null),
		dut ("nl", "Nederlands", "Dutch, Flemish", null),
		dyu (null, "Julakan", "Dyula", null),
		dzo ("dz", "རྫོང་�?", "Dzongkha", "\u0f62\u0fab\u0f7c\u0f44\u0f0b\u0f41"),
		
		efi (null, "Efik", "Efik", "\u00e9\u0066\u0069\u006b"),
		egy (null, null, "Egyptian  (Ancient)", null),
		eka (null, "Ekajuk", "Ekajuk", null),
		ell ("el", "Ελληνικά", "Modern Greek  (since 1453–)", "\u0395\u03bb\u03bb\u03b7\u03bd\u03b9\u03ba\u03ac"),
		elx (null, null, "Elamite", null), // No native language available
		eng ("en", "English", "English", null),
		enm (null, null, "English, Middle  (ca. 1100–1500)", null),
		epo ("eo", "Esperanto", "Esperanto", null),
		est ("et", "Eesti keel", "Estonian", null),
		eus ("eu", "Euskara", "Basque", null),
		ewe ("ee", "�?ʋɛgbɛ", "Ewe", "\u0190\u028b\u025b\u0067\u0062\u025b"),
		ewo (null, "Ewondo", "Ewondo", "\u00e9\u0077\u006f\u006e\u0064\u006f"),

		fan (null, "Fang", "Fang", null),
		fao ("fo", "Føroyskt", "Faroese", "\u0046\u00f8\u0072\u006f\u0079\u0073\u006b\u0074"),
		fas ("fa", "�?ارسی", "Persian", "\u0641\u0627\u0631\u0633\u06cc"),
		fat (null, "Fanti", "Fanti", null),
		fij ("fj", "Vosa Vakaviti", "Fijian", null),
		fil (null, "filipino", "Filipino", null),
		fin ("fi", "Suomi, suomen kieli", "Finnish", null),
		fiu (null, null, "Finno-Ugrian languages", null),
		fon (null, "Fɔngbe", "Fon", "\u0046\u0254\u006e\u0067\u0062\u0065"),
		fra ("fr", "Français", "French", null),
		fre ("fr", "Français", "French", null),
		frm (null, null, "Middle French  (ca. 1400—1600)", null),
		fro (null, null, "Old French  (842—ca. 1400)", null),
		frr (null, "Fräisk", "Northern Frisian", null),
		frs (null, "Seeltersk Fräisk, Seeltersk, Fräisk", "Eastern Frisian", null),
		fry ("fy", "Frysk", "Western Frisian", null),
		ful ("ff", "Fulfulde, Pulaar, Pular", "Fulah", null),
		fur (null, "Furlan", "Friulian", null),

		gaa ("ga", "Gã", "Ga", "\u0047\u00e3"),
		gay (null, "Gayo", "Gayo", null),
		gba (null, "Gbaya", "Gbaya", null),
		gem (null, null, "Germanic languages", null),
		geo ("ka", "ქ�?რთული ენ�?  (kartuli ena)", "Georgian", "\u10e5\u10d0\u10e0\u10d7\u10e3\u10da\u10d8 \u10d4\u10dc\u10d0 \u0028\u006b\u0061\u0072\u0074\u0075\u006c\u0069 \u0065\u006e\u0061\u0029"),
		ger ("de", "Deutsch", "German", null),
		gez (null, "�?ዕ�?", "Ge'ez", "\u130d\u12d5\u12dd"),
		gil (null, "Taetae ni Kiribati", "Gilbertese", null),
		gla ("gd", "Gàidhlig", "Scottish Gaelic, Gaelic", null),
		gle ("ga", "Gaeilge", "Irish", null),
		glg ("gl", "Galego", "Galician", null),
		glv ("gv", "Gaelg, Manninagh", "Manx", null),
		gmh (null, "Diutisk", "Middle High German  (ca. 1050–1500)", null),
		goh (null, "Diutisc", "Old High German  (ca. 750–1050)", null),
		gon (null, "G�?ndi", "Gondi", null),
		gor (null, "Gorontalo", "Gorontalo", null),
		got (null, "�?���?���??��?���??��?��", "Gothic", "\ud800\udf32\ud800\udf3f\ud800\udf44\ud800\udf39\ud800\udf43\ud800\udf3a"),
		grb (null, "Grébo", "Grebo", null),
		grc (null, "Ἑλληνικά", "Ancient Greek  (to 1453)", "\u1f19\u03bb\u03bb\u03b7\u03bd\u03b9\u03ba\u03ac"),
		gre ("el", "Ελληνικά", "Modern Greek  (since 1453–)", "\u1f19\u03bb\u03bb\u03b7\u03bd\u03b9\u03ba\u03ac"),
		grn ("gn", "Avañe'ẽ", "Guarani", "\u0041\u0076\u0061\u00f1\u0065\u0027\u1ebd"),
		gsw (null, "Alemannisch, Schwyzerdütsch, Elsässisch", "Swiss German, Alemannic, Alsatian", null),
		guj ("gu", "ગ�?જરાતી", "Gujarati", "\u0a97\u0ac1\u0a9c\u0ab0\u0abe\u0aa4\u0ac0"),
		gwi (null, "Gwich'in", "Gwichʼin", null),

		hai (null, "X̲aat Kíl", "Haida", "\u0058\u0332\u0061\u0061\u0074 \u004b\u00ed\u006c"),
		hat ("ht", "Kreyòl ayisyen", "Haitian Creole, Haitian", null),
		hau ("ha", "Hausancī, هَو�?سَ", "Hausa", "\u0048\u0061\u0075\u0073\u0061\u006e\u0063\u012b\u002c \u0647\u064e\u0648\u064f\u0633\u064e"),
		haw (null, "‘Ōlelo Hawai‘i", "Hawaiian", "\u2018\u014c\u006c\u0065\u006c\u006f \u0048\u0061\u0077\u0061\u0069\u2018\u0069"),
		heb ("he", "עִבְרִית, עברית", "Hebrew", "\u05e2\u05b4\u05d1\u05b0\u05e8\u05b4\u05d9\u05ea\u002c \u05e2\u05d1\u05e8\u05d9\u05ea"),
		her ("hz", "Otjiherero", "Herero", null),
		hil (null, "Ilonggo", "Hiligaynon", null),
		him (null, "Himachali", "Himachali", null),
		hin ("hi", "हिन�?दी", "Hindi", "\u0939\u093f\u0928\u094d\u0926\u0940"),
		hit (null, "Hittite", "Hittite", null),
		hmn (null, "Hmoob", "Hmong", ""),
		hmo ("ho", "Hiri Motu", "Hiri Motu", ""),
		hrv ("hr", "hrvatski", "Croatian", ""),
		hsb (null, "hornjoserbsce", "Upper Sorbian", ""),
		hun ("hu", "Magyar", "Hungarian", ""),
		hup (null, "Na:tinixwe Mixine:whe", "Hupa", ""),
		hye ("hy", "Հայերեն լեզու", "Armenian", ""),

		iba (null, "Iban", "Iban", null),
		ibo ("ig", "Igbo", "Igbo", null),
		ice ("is", "íslenska", "Icelandic", null),
		ido ("io", "Ido", "Ido", null),
		iii ("ii", "ꆇꉙ", "Sichuan Yi, Nuosu", "\ua187\ua259"),
		ijo (null, null, "Ijo languages", null),
		iku ("iu", "�?�ᓄᒃᑎ�?ᑦ", "	Inuktitut", "\u1403\u14c4\u1483\u144e\u1450\u1466"),
		ile ("ie", "Interlingue", "Interlingue, Occidental", null),
		ilo (null, "ilocano", "Iloko", null),
		ina ("ia", "interlingua", "Interlingua  (International Auxiliary Language Association", null),
		inc (null, null, "Indic languages", null),
		ind ("id", "Bahasa Indonesia", "Indonesian", null),
		ine (null, null, "Indo-European languages", null),
		inh (null, "гӀалгӀай мотт", "Ingush", "\u0433\u04c0\u0430\u043b\u0433\u04c0\u0430\u0439 \u043c\u043e\u0442\u0442"),
		ipk ("ik", "Iñupiaq, Iñupiatun", "Inupiaq", null),
		ira (null, null, "Iranian languages", null),
		iro (null, null, "Iroquoian languages", null),
		isl ("is", "Islenska", "Icelandic", null),
		ita ("it", "Italiano", "Italian", null),

		jav ("jv", "Basa Jawa", "Javanese", null),
		jbo (null, "Lojban", "Lojban", null),
		jpn ("ja", "日本語", "Japanese", "\u65e5\u672c\u8a9e"), // Japanese chars do not render
		jpr (null, null, "Judeo-Persian", null),
		jrb (null, null, "Judeo-Arabic", null),

		kaa (null, "қарақалпақ тили", "Kara-Kalpak", "\u049b\u0430\u0440\u0430\u049b\u0430\u043b\u043f\u0430\u049b \u0442\u0438\u043b\u0438"),
		kab (null, "Taqbaylit", "Kabyle", null),
		kac (null, "Jingpho, Marip", "Kachin, Jingpho", null),
		kal ("kl", "kalaallisut, kalaallit oqaasii", "Greenlandic, Kalaallisut", null),
		kam (null, "Kamba", "Kamba", null),
		kan ("kn", "ಕನ�?ನಡ", "Kannada", "\u0c95\u0ca8\u0ccd\u0ca8\u0ca1"),
		kar (null, null, "Karen languages", null),
		kas ("ks", "कॉश�?र, کٲش�?ر", "Kashmiri", "\u0915\u0949\u0936\u0941\u0930\u002c \u06a9\u0672\u0634\u064f\u0631"),
		kat ("ka", "ქ�?რთული ენ�?  (kartuli ena)", "Georgian", "\u10e5\u10d0\u10e0\u10d7\u10e3\u10da\u10d8 \u10d4\u10dc\u10d0 \u0028\u006b\u0061\u0072\u0074\u0075\u006c\u0069 \u0065\u006e\u0061\u0029"),
		kau ("kr", "Kanouri", "Kanuri", null),
		kaw (null, "Bh�?ṣa Kawi", "Kawi", null),
		kaz ("kk", "Қазақ тілі", "Kazakh", "\u049a\u0430\u0437\u0430\u049b \u0442\u0456\u043b\u0456"),
		kbd (null, "къ�?б�?рдеибз�?", "Kabardian", "\u043a\u044a\u044d\u0431\u044d\u0440\u0434\u0435\u0438\u0431\u0437\u044d"),
		kha (null, "Khasi", "Khasi", null),
		khi (null, null, "Khoisan languages", null),
		khm ("km", "ភាសា�?្មែរ", "Central Khmer", "\u1797\u17b6\u179f\u17b6\u1781\u17d2\u1798\u17c2\u179a"),
		kho (null, "Sakan", "Khotanese, Sakan", null),
		kik ("ki", "Gĩkũyũ", "Kikuyu, Gikuyu", "\u0047\u0129\u006b\u0169\u0079\u0169"),
		kim (null, "Kimboundou", "Kimbundu", null),
		kin ("rw", "KinyaRwanda", "Kinyarwanda", null),
		kir ("ky", "кыргыз тили", "Kirghiz", "\u043a\u044b\u0440\u0433\u044b\u0437 \u0442\u0438\u043b\u0438"),
		kmb (null, "Kimboundou", "Kimbundu", null),
		kok (null, "कोंकणी", "Konkani", "\u0915\u094b\u0902\u0915\u0923\u0940"),
		kom ("kv", "коми кыв", "Komi", "\u043a\u043e\u043c\u0438 \u043a\u044b\u0432"),
		kon ("kg", "Kikongo", "Kongo", null),
		kor ("ko", "한국어", "Korean", "\ud55c\uad6d\uc5b4"),
		kos (null, "Kosrae", "Kosraean", null),
		kpe (null, "Kpele", "Kpelle", null),
		krc (null, "къарачай-малкъар тил", "Karachay-Balkar", "\u043a\u044a\u0430\u0440\u0430\u0447\u0430\u0439\u002d\u043c\u0430\u043b\u043a\u044a\u0430\u0440 \u0442\u0438\u043b"),
		krl (null, "karjalan kieli", "Karelian", null),
		kro (null, null, "Kru languages", null),
		kru (null, "kouroukh", "Kurukh", null),
		kua ("kj", "Kuanyama, kwanyama", "Kuanyama, Kwanyama", null),
		kum (null, "Кумык", "Kumyk", "\u041a\u0443\u043c\u044b\u043a"),
		kur ("ku", "كوردی, Kurdî", "Kurdish", "\u0643\u0648\u0631\u062f\u06cc\u002c \u004b\u0075\u0072\u0064\u00ee"),
		kut (null, "Ktunaxa", "Kutenai", null),

		lad (null, "ג'ודי�?ו-�?יספ�?נייול", "Ladino", "\u0643\u0648\u0631\u062f\u06cc\u05d2\u0027\u05d5\u05d3\u05d9\u05d0\u05d5\u002d\u05d0\u05d9\u05e1\u05e4\u05d0\u05e0\u05d9\u05d9\u05d5\u05dc"),
		lah (null, "ਲਹਿੰਦੀ", "Lahnda", "\u0a32\u0a39\u0a3f\u0a70\u0a26\u0a40"),
		lam (null, "Lamba", "Lamba", null),
		lao ("lo", "ພາສາລາວ", "Lao", "\u0e9e\u0eb2\u0eaa\u0eb2\u0ea5\u0eb2\u0ea7"),
		lat ("la", "Latine, lingua latina", "Latin", null),
		lav ("lv", "Latviešu valoda", "Latvian", "\u004c\u0061\u0074\u0076\u0069\u0065\u0161\u0075 \u0076\u0061\u006c\u006f\u0064\u0061"),
		lez (null, "лезги чӀал", "Lezghian", "\u043b\u0435\u0437\u0433\u0438 \u0447\u04c0\u0430\u043b"),
		lim ("li", "Limburgs", "Limburgish, Limburger, Limburgan", null),
		lin ("ln", "Lingála", "Lingala", null),
		lit ("lt", "Lietuvių kalba", "Lithuanian", "\u004c\u0069\u0065\u0074\u0075\u0076\u0069\u0173 \u006b\u0061\u006c\u0062\u0061"),
		lol (null, "Mongo", "Mongo", null),
		loz (null, "siLozi", "Lozi", null),
		ltz ("lb", "Lëtzebuergesch", "Luxembourgish, Letzeburgesch", null),
		lua (null, "lwaà:", "Luba-Lulua", null),
		lub ("lu", "Kiluba", "Luba-Katanga", null),
		lug ("lg", "Luganda", "Ganda", null),
		lui (null, "Luiseño", "Luiseño", null),
		lun (null, "chiLunda", "Lunda", null),
		luo (null, "Dholuo", "Luo", null),
		lus (null, "Lousaï", "Lushai", null),

		mac ("mk", "македон�?ки јазик", "Macedonian", "\u043c\u0430\u043a\u0435\u0434\u043e\u043d\u0441\u043a\u0438 \u0458\u0430\u0437\u0438\u043a"),
		mad (null, "Madurais", "Madurese", null),
		mag (null, "Magahi", "Magahi", null),
		mah ("mh", "Kajin M̧ajeļ", "Marshallese", null),
		mai (null, "मैथिली", "Maithili", "\u092e\u0948\u0925\u093f\u0932\u0940"),
		mak (null, "Makassar", "Makasar", null),
		mal ("ml", "മലയാളം", "Malayalam", "\u0d2e\u0d32\u0d2f\u0d3e\u0d33\u0d02"),
		man (null, "Mandingue", "Mandingo", null),
		mao ("mi", "te reo M�?ori", "Maori", null),
		map (null, null, "Austronesian languages", null),
		mar ("mr", "मराठी", "Marathi", "\u092e\u0930\u093e\u0920\u0940"),
		mas (null, "ɔl Maa", "Masai", "\u0254\u006c \u004d\u0061\u0061"),
		may ("ms", "bahasa Melayu, بهاس ملايو", "Malay", "\u0062\u0061\u0068\u0061\u0073\u0061 \u004d\u0065\u006c\u0061\u0079\u0075\u002c \u0628\u0647\u0627\u0633 \u0645\u0644\u0627\u064a\u0648"),
		mdf (null, "мокшень к�?ль", "Moksha", "\u043c\u043e\u043a\u0448\u0435\u043d\u044c \u043a\u044f\u043b\u044c"),
		mdr (null, "Mandar", "Mandar", null),
		men (null, "Mɛnde", "Mende", "\u004d\u025b\u006e\u0064\u0065"),
		mga (null, "Gaoidhealg", "Middle Irish  (900–1200)", null),
		mic (null, "Míkmaq, Mi'gmaq", "Mi'kmaq, Micmac", null),
		min (null, "Baso Minangkabau", "Minangkabau", null),
		mis (null, null, "Uncoded languages", null),
		mkd ("mk", "македон�?ки јазик", "Macedonian", "\u043c\u0430\u043a\u0435\u0434\u043e\u043d\u0441\u043a\u0438 \u0458\u0430\u0437\u0438\u043a"),
		mkh (null, null, "Mon-Khmer languages", null),
		mlg ("mg", "Malagasy fiteny", "Malagasy", null),
		mlt ("mt", "Malti", "Maltese", null),
		mnc (null, "ᠮᠠᠨᠵᡠ ᡤᡳᠰᡠᠨ ᠪ�?", "Manchu", "\u182e\u1820\u1828\u1835\u1860 \u1864\u1873\u1830\u1860\u1828 \u182a\u185d"),
		mni (null, "মৈইতৈইলোন", "Manipuri", "\u09ae\u09c8\u0987\u09a4\u09c8\u0987\u09b2\u09cb\u09a8"),
		mno (null, null, "Manobo languages", null),
		moh (null, "Kanien’keha", "Mohawk", null),
		mol ("mo", "лимба молдовен�?�?к�?", "Moldavian", "\u043b\u0438\u043c\u0431\u0430 \u043c\u043e\u043b\u0434\u043e\u0432\u0435\u043d\u044f\u0441\u043a\u044d"),
		mon ("mn", "монгол х�?л", "Mongolian", "\u043c\u043e\u043d\u0433\u043e\u043b \u0445\u044d\u043b"),
		mos (null, "Mòoré", "Mossi", null),
		mri ("mi", "te reo M�?ori", "Maori", null),
		msa ("ms", "bahasa Melayu, بهاس ملايو", "Malay", "\u0062\u0061\u0068\u0061\u0073\u0061 \u004d\u0065\u006c\u0061\u0079\u0075\u002c \u0628\u0647\u0627\u0633 \u0645\u0644\u0627\u064a\u0648"),
		mul (null, null, "Multiple languages", null),
		mun (null, null, "Munda languages", null),
		mus (null, "Maskoki, Mvskokē empunakv", "Creek", null),
		mwl (null, "Lhéngua Mirandesa", "Mirandese", null),
		mwr (null, "मारवाड़ी", "Marwari", "\u092e\u093e\u0930\u0935\u093e\u0921\u093c\u0940"),
		mya ("my", "မျန္မာစာ", "Burmese", ""),
		myn (null, null, "Mayan languages", null),
		myv (null, "�?рз�?нь кель", "Erzya", "\u044d\u0440\u0437\u044f\u043d\u044c \u043a\u0435\u043b\u044c"),
	
		nah (null, "N�?huatl, nawatlahtolli", "Nahuatl languages", null),
		nai (null, null, "North American Indian languages", null),
		nap (null, "Napulitano", "Neapolitan", null),
		nau ("na", "Ekakairũ Naoero", "Nauruan", null),
		nav ("nv", "Diné bizaad, Dinékʼehǰí", "Navajo, Navaho", "\u0044\u0069\u006e\u00e9 \u0062\u0069\u007a\u0061\u0061\u0064\u002c \u0044\u0069\u006e\u00e9\u006b\u02bc\u0065\u0068\u01f0\u00ed"),
		nbl ("nr", "Ndébélé", "South Ndebele", null),
		nde ("nd", "isiNdebele", "North Ndebele", null),
		ndo ("ng", "Owambo", "Ndonga", null),
		nds (null, "Nederdüütsch, Plattdüütsch", "Low German, Low Saxon", null),
		nep ("ne", "नेपाली", "Nepali", "\u0928\u0947\u092a\u093e\u0932\u0940"),
		newb (null, "Nepal Bhasa", "Nepal Bhasa, Newari", null), // special handling, return "new" instead of "newb"
		nia (null, "Nias", "Nias", null),
		nic (null, null, "Niger-Kordofanian languages", null),
		niu (null, "ko e vagahau Niuē, faka-Niue", "Niuean", null),
		nld ("nl", "Nederlands", "Dutch, Flemish", ""),
		nno ("nn", "Norsk nynorsk", "Norwegian Nynorsk", null),
		nob ("nb", "Norsk bokmål", "Norwegian Bokmål", null),
		nog (null, "ногай тили", "Nogai", "\u043d\u043e\u0433\u0430\u0439 \u0442\u0438\u043b\u0438"),
		non (null, "Norskr", "Norse, Old", null),
		nor ("no", "Norsk", "Norwegian", null),
		nqo (null, "N'ko", "N'Ko", null),
		nso (null, "sePêdi", "Northern Sotho, Pedi, Sepedi", null),
		nub  (null, null, "Nubian languages", null),
		nwc (null, "Newari", "Classical Newari, Old Newari, Classical Nepal Bhasa", null), // No original language available
		nya ("ny", "chiCheŵa, chinyanja", "Chichewa, Chewa, Nyanja", null),
		nym (null, "Kinyamwezi", "Nyamwezi", null),
		nyn (null, "Lounyankolé", "Nyankole", null),
		nyo (null, "Runyoro", "Nyoro", null),
		nzi (null, "Nzéma", "Nzima", null),

		oci ("oc", "Occitan", "Occitan  (post 1500), Provençal", null),
		oji ("oj", "�?�ᓂᔑᓇ�?�ᒧ�??�?�", "Ojibwa", "\u140a\u14c2\u1511\u14c7\u142f\u14a7\u140f\u1423"),
		ori ("or", "ଓଡ଼ିଆ", "Oriya", "\u0b13\u0b21\u0b3c\u0b3f\u0b06"),
		orm ("om", "Afaan Oromoo", "Oromo", null),
		osa (null, "Osage", "Osage", null),
		oss ("os", "ирон ӕвзаг", "Ossetian, Ossetic", "\u0438\u0440\u043e\u043d \u04d5\u0432\u0437\u0430\u0433"),
		ota (null, null, "Ottoman Turkish  (1500–1928)", null),
		oto (null, null, "Otomian languages", null),
		
		paa (null, null, "Papuan languages", null),
		pag (null, "Pangasinan", "Pangasinan", null),
		pal (null, "Pèhlevî", "Pahlavi  (Middle Persian)", null),
		pam (null, "Kapampangan", "Pampanga, Kapampangan", null),
		pan ("pa", "ਪੰਜਾਬੀ, پنجابی", "Punjabi, Panjabi", "\u0a2a\u0a70\u0a1c\u0a3e\u0a2c\u0a40\u002c \u067e\u0646\u062c\u0627\u0628\u06cc"), 
		pap (null, "Papiamentu", "Papiamento", null),
		pau (null, "tekoi ra Belau", "Palauan", null),
		peo (null, null, "Old Persian  (ca. 600–400 BC)", null),
		per ("fa", "�?ارسی", "Persian", "\u0641\u0627\u0631\u0633\u06cc"),
		phi (null, null, "Philippine languages", null),
		phn (null, null, "Phoenician", null),
		pli ("pi", "पालि", "Pali", "\u092a\u093e\u0932\u093f"),
		pol ("pl", "Polski", "Polish", null),
		pon (null, "Pohnpei", "Pohnpeian", null),
		por ("pt", "Português", "Portuguese", null),
		pra (null, null, "Prakrit languages", null),
		pro (null, "Provençal ancien, occitan ancien  (jusqu'à 1500)", "Old Provençal, Old Occitan  (to 1500)", null),
		pus ("ps", "پښت", "Pushto, Pashto", "\u067e\u069a\u062a"),
		
		// [qaa-qtz] range is "Reserved for local use".
		// There is no elegant/smooth method to avoid this tedious way of doing, as an enum is a static class. 
		qaa (null, null, "Reserved for local use", null),
		qab (null, null, "Reserved for local use", null),
		qac (null, null, "Reserved for local use", null),
		qad (null, null, "Reserved for local use", null),
		qae (null, null, "Reserved for local use", null),
		qaf (null, null, "Reserved for local use", null),
		qag (null, null, "Reserved for local use", null),
		qah (null, null, "Reserved for local use", null),
		qai (null, null, "Reserved for local use", null),
		qaj (null, null, "Reserved for local use", null),
		qak (null, null, "Reserved for local use", null),
		qal (null, null, "Reserved for local use", null),
		qam (null, null, "Reserved for local use", null),
		qan (null, null, "Reserved for local use", null),
		qao (null, null, "Reserved for local use", null),
		qap (null, null, "Reserved for local use", null),
		qaq (null, null, "Reserved for local use", null),
		qar (null, null, "Reserved for local use", null),
		qas (null, null, "Reserved for local use", null),
		qat (null, null, "Reserved for local use", null),
		qau (null, null, "Reserved for local use", null),
		qav (null, null, "Reserved for local use", null),
		qaw (null, null, "Reserved for local use", null),
		qax (null, null, "Reserved for local use", null),
		qay (null, null, "Reserved for local use", null),
		qaz (null, null, "Reserved for local use", null),
		qba (null, null, "Reserved for local use", null),
		qbb (null, null, "Reserved for local use", null),
		qbc (null, null, "Reserved for local use", null),
		qbd (null, null, "Reserved for local use", null),
		qbe (null, null, "Reserved for local use", null),
		qbf (null, null, "Reserved for local use", null),
		qbg (null, null, "Reserved for local use", null),
		qbh (null, null, "Reserved for local use", null),
		qbi (null, null, "Reserved for local use", null),
		qbj (null, null, "Reserved for local use", null),
		qbk (null, null, "Reserved for local use", null),
		qbl (null, null, "Reserved for local use", null),
		qbm (null, null, "Reserved for local use", null),
		qbn (null, null, "Reserved for local use", null),
		qbo (null, null, "Reserved for local use", null),
		qbp (null, null, "Reserved for local use", null),
		qbq (null, null, "Reserved for local use", null),
		qbr (null, null, "Reserved for local use", null),
		qbs (null, null, "Reserved for local use", null),
		qbt (null, null, "Reserved for local use", null),
		qbu (null, null, "Reserved for local use", null),
		qbv (null, null, "Reserved for local use", null),
		qbw (null, null, "Reserved for local use", null),
		qbx (null, null, "Reserved for local use", null),
		qby (null, null, "Reserved for local use", null),
		qbz (null, null, "Reserved for local use", null),
		qca (null, null, "Reserved for local use", null),
		qcb (null, null, "Reserved for local use", null),
		qcc (null, null, "Reserved for local use", null),
		qcd (null, null, "Reserved for local use", null),
		qce (null, null, "Reserved for local use", null),
		qcf (null, null, "Reserved for local use", null),
		qcg (null, null, "Reserved for local use", null),
		qch (null, null, "Reserved for local use", null),
		qci (null, null, "Reserved for local use", null),
		qcj (null, null, "Reserved for local use", null),
		qck (null, null, "Reserved for local use", null),
		qcl (null, null, "Reserved for local use", null),
		qcm (null, null, "Reserved for local use", null),
		qcn (null, null, "Reserved for local use", null),
		qco (null, null, "Reserved for local use", null),
		qcp (null, null, "Reserved for local use", null),
		qcq (null, null, "Reserved for local use", null),
		qcr (null, null, "Reserved for local use", null),
		qcs (null, null, "Reserved for local use", null),
		qct (null, null, "Reserved for local use", null),
		qcu (null, null, "Reserved for local use", null),
		qcv (null, null, "Reserved for local use", null),
		qcw (null, null, "Reserved for local use", null),
		qcx (null, null, "Reserved for local use", null),
		qcy (null, null, "Reserved for local use", null),
		qcz (null, null, "Reserved for local use", null),
		qda (null, null, "Reserved for local use", null),
		qdb (null, null, "Reserved for local use", null),
		qdc (null, null, "Reserved for local use", null),
		qdd (null, null, "Reserved for local use", null),
		qde (null, null, "Reserved for local use", null),
		qdf (null, null, "Reserved for local use", null),
		qdg (null, null, "Reserved for local use", null),
		qdh (null, null, "Reserved for local use", null),
		qdi (null, null, "Reserved for local use", null),
		qdj (null, null, "Reserved for local use", null),
		qdk (null, null, "Reserved for local use", null),
		qdl (null, null, "Reserved for local use", null),
		qdm (null, null, "Reserved for local use", null),
		qdn (null, null, "Reserved for local use", null),
		qdo (null, null, "Reserved for local use", null),
		qdp (null, null, "Reserved for local use", null),
		qdq (null, null, "Reserved for local use", null),
		qdr (null, null, "Reserved for local use", null),
		qds (null, null, "Reserved for local use", null),
		qdt (null, null, "Reserved for local use", null),
		qdu (null, null, "Reserved for local use", null),
		qdv (null, null, "Reserved for local use", null),
		qdw (null, null, "Reserved for local use", null),
		qdx (null, null, "Reserved for local use", null),
		qdy (null, null, "Reserved for local use", null),
		qdz (null, null, "Reserved for local use", null),
		qea (null, null, "Reserved for local use", null),
		qeb (null, null, "Reserved for local use", null),
		qec (null, null, "Reserved for local use", null),
		qed (null, null, "Reserved for local use", null),
		qee (null, null, "Reserved for local use", null),
		qef (null, null, "Reserved for local use", null),
		qeg (null, null, "Reserved for local use", null),
		qeh (null, null, "Reserved for local use", null),
		qei (null, null, "Reserved for local use", null),
		qej (null, null, "Reserved for local use", null),
		qek (null, null, "Reserved for local use", null),
		qel (null, null, "Reserved for local use", null),
		qem (null, null, "Reserved for local use", null),
		qen (null, null, "Reserved for local use", null),
		qeo (null, null, "Reserved for local use", null),
		qep (null, null, "Reserved for local use", null),
		qeq (null, null, "Reserved for local use", null),
		qer (null, null, "Reserved for local use", null),
		qes (null, null, "Reserved for local use", null),
		qet (null, null, "Reserved for local use", null),
		qeu (null, null, "Reserved for local use", null),
		qev (null, null, "Reserved for local use", null),
		qew (null, null, "Reserved for local use", null),
		qex (null, null, "Reserved for local use", null),
		qey (null, null, "Reserved for local use", null),
		qez (null, null, "Reserved for local use", null),
		qfa (null, null, "Reserved for local use", null),
		qfb (null, null, "Reserved for local use", null),
		qfc (null, null, "Reserved for local use", null),
		qfd (null, null, "Reserved for local use", null),
		qfe (null, null, "Reserved for local use", null),
		qff (null, null, "Reserved for local use", null),
		qfg (null, null, "Reserved for local use", null),
		qfh (null, null, "Reserved for local use", null),
		qfi (null, null, "Reserved for local use", null),
		qfj (null, null, "Reserved for local use", null),
		qfk (null, null, "Reserved for local use", null),
		qfl (null, null, "Reserved for local use", null),
		qfm (null, null, "Reserved for local use", null),
		qfn (null, null, "Reserved for local use", null),
		qfo (null, null, "Reserved for local use", null),
		qfp (null, null, "Reserved for local use", null),
		qfq (null, null, "Reserved for local use", null),
		qfr (null, null, "Reserved for local use", null),
		qfs (null, null, "Reserved for local use", null),
		qft (null, null, "Reserved for local use", null),
		qfu (null, null, "Reserved for local use", null),
		qfv (null, null, "Reserved for local use", null),
		qfw (null, null, "Reserved for local use", null),
		qfx (null, null, "Reserved for local use", null),
		qfy (null, null, "Reserved for local use", null),
		qfz (null, null, "Reserved for local use", null),
		qga (null, null, "Reserved for local use", null),
		qgb (null, null, "Reserved for local use", null),
		qgc (null, null, "Reserved for local use", null),
		qgd (null, null, "Reserved for local use", null),
		qge (null, null, "Reserved for local use", null),
		qgf (null, null, "Reserved for local use", null),
		qgg (null, null, "Reserved for local use", null),
		qgh (null, null, "Reserved for local use", null),
		qgi (null, null, "Reserved for local use", null),
		qgj (null, null, "Reserved for local use", null),
		qgk (null, null, "Reserved for local use", null),
		qgl (null, null, "Reserved for local use", null),
		qgm (null, null, "Reserved for local use", null),
		qgn (null, null, "Reserved for local use", null),
		qgo (null, null, "Reserved for local use", null),
		qgp (null, null, "Reserved for local use", null),
		qgq (null, null, "Reserved for local use", null),
		qgr (null, null, "Reserved for local use", null),
		qgs (null, null, "Reserved for local use", null),
		qgt (null, null, "Reserved for local use", null),
		qgu (null, null, "Reserved for local use", null),
		qgv (null, null, "Reserved for local use", null),
		qgw (null, null, "Reserved for local use", null),
		qgx (null, null, "Reserved for local use", null),
		qgy (null, null, "Reserved for local use", null),
		qgz (null, null, "Reserved for local use", null),
		qha (null, null, "Reserved for local use", null),
		qhb (null, null, "Reserved for local use", null),
		qhc (null, null, "Reserved for local use", null),
		qhd (null, null, "Reserved for local use", null),
		qhe (null, null, "Reserved for local use", null),
		qhf (null, null, "Reserved for local use", null),
		qhg (null, null, "Reserved for local use", null),
		qhh (null, null, "Reserved for local use", null),
		qhi (null, null, "Reserved for local use", null),
		qhj (null, null, "Reserved for local use", null),
		qhk (null, null, "Reserved for local use", null),
		qhl (null, null, "Reserved for local use", null),
		qhm (null, null, "Reserved for local use", null),
		qhn (null, null, "Reserved for local use", null),
		qho (null, null, "Reserved for local use", null),
		qhp (null, null, "Reserved for local use", null),
		qhq (null, null, "Reserved for local use", null),
		qhr (null, null, "Reserved for local use", null),
		qhs (null, null, "Reserved for local use", null),
		qht (null, null, "Reserved for local use", null),
		qhu (null, null, "Reserved for local use", null),
		qhv (null, null, "Reserved for local use", null),
		qhw (null, null, "Reserved for local use", null),
		qhx (null, null, "Reserved for local use", null),
		qhy (null, null, "Reserved for local use", null),
		qhz (null, null, "Reserved for local use", null),
		qia (null, null, "Reserved for local use", null),
		qib (null, null, "Reserved for local use", null),
		qic (null, null, "Reserved for local use", null),
		qid (null, null, "Reserved for local use", null),
		qie (null, null, "Reserved for local use", null),
		qif (null, null, "Reserved for local use", null),
		qig (null, null, "Reserved for local use", null),
		qih (null, null, "Reserved for local use", null),
		qii (null, null, "Reserved for local use", null),
		qij (null, null, "Reserved for local use", null),
		qik (null, null, "Reserved for local use", null),
		qil (null, null, "Reserved for local use", null),
		qim (null, null, "Reserved for local use", null),
		qin (null, null, "Reserved for local use", null),
		qio (null, null, "Reserved for local use", null),
		qip (null, null, "Reserved for local use", null),
		qiq (null, null, "Reserved for local use", null),
		qir (null, null, "Reserved for local use", null),
		qis (null, null, "Reserved for local use", null),
		qit (null, null, "Reserved for local use", null),
		qiu (null, null, "Reserved for local use", null),
		qiv (null, null, "Reserved for local use", null),
		qiw (null, null, "Reserved for local use", null),
		qix (null, null, "Reserved for local use", null),
		qiy (null, null, "Reserved for local use", null),
		qiz (null, null, "Reserved for local use", null),
		qja (null, null, "Reserved for local use", null),
		qjb (null, null, "Reserved for local use", null),
		qjc (null, null, "Reserved for local use", null),
		qjd (null, null, "Reserved for local use", null),
		qje (null, null, "Reserved for local use", null),
		qjf (null, null, "Reserved for local use", null),
		qjg (null, null, "Reserved for local use", null),
		qjh (null, null, "Reserved for local use", null),
		qji (null, null, "Reserved for local use", null),
		qjj (null, null, "Reserved for local use", null),
		qjk (null, null, "Reserved for local use", null),
		qjl (null, null, "Reserved for local use", null),
		qjm (null, null, "Reserved for local use", null),
		qjn (null, null, "Reserved for local use", null),
		qjo (null, null, "Reserved for local use", null),
		qjp (null, null, "Reserved for local use", null),
		qjq (null, null, "Reserved for local use", null),
		qjr (null, null, "Reserved for local use", null),
		qjs (null, null, "Reserved for local use", null),
		qjt (null, null, "Reserved for local use", null),
		qju (null, null, "Reserved for local use", null),
		qjv (null, null, "Reserved for local use", null),
		qjw (null, null, "Reserved for local use", null),
		qjx (null, null, "Reserved for local use", null),
		qjy (null, null, "Reserved for local use", null),
		qjz (null, null, "Reserved for local use", null),
		qka (null, null, "Reserved for local use", null),
		qkb (null, null, "Reserved for local use", null),
		qkc (null, null, "Reserved for local use", null),
		qkd (null, null, "Reserved for local use", null),
		qke (null, null, "Reserved for local use", null),
		qkf (null, null, "Reserved for local use", null),
		qkg (null, null, "Reserved for local use", null),
		qkh (null, null, "Reserved for local use", null),
		qki (null, null, "Reserved for local use", null),
		qkj (null, null, "Reserved for local use", null),
		qkk (null, null, "Reserved for local use", null),
		qkl (null, null, "Reserved for local use", null),
		qkm (null, null, "Reserved for local use", null),
		qkn (null, null, "Reserved for local use", null),
		qko (null, null, "Reserved for local use", null),
		qkp (null, null, "Reserved for local use", null),
		qkq (null, null, "Reserved for local use", null),
		qkr (null, null, "Reserved for local use", null),
		qks (null, null, "Reserved for local use", null),
		qkt (null, null, "Reserved for local use", null),
		qku (null, null, "Reserved for local use", null),
		qkv (null, null, "Reserved for local use", null),
		qkw (null, null, "Reserved for local use", null),
		qkx (null, null, "Reserved for local use", null),
		qky (null, null, "Reserved for local use", null),
		qkz (null, null, "Reserved for local use", null),
		qla (null, null, "Reserved for local use", null),
		qlb (null, null, "Reserved for local use", null),
		qlc (null, null, "Reserved for local use", null),
		qld (null, null, "Reserved for local use", null),
		qle (null, null, "Reserved for local use", null),
		qlf (null, null, "Reserved for local use", null),
		qlg (null, null, "Reserved for local use", null),
		qlh (null, null, "Reserved for local use", null),
		qli (null, null, "Reserved for local use", null),
		qlj (null, null, "Reserved for local use", null),
		qlk (null, null, "Reserved for local use", null),
		qll (null, null, "Reserved for local use", null),
		qlm (null, null, "Reserved for local use", null),
		qln (null, null, "Reserved for local use", null),
		qlo (null, null, "Reserved for local use", null),
		qlp (null, null, "Reserved for local use", null),
		qlq (null, null, "Reserved for local use", null),
		qlr (null, null, "Reserved for local use", null),
		qls (null, null, "Reserved for local use", null),
		qlt (null, null, "Reserved for local use", null),
		qlu (null, null, "Reserved for local use", null),
		qlv (null, null, "Reserved for local use", null),
		qlw (null, null, "Reserved for local use", null),
		qlx (null, null, "Reserved for local use", null),
		qly (null, null, "Reserved for local use", null),
		qlz (null, null, "Reserved for local use", null),
		qma (null, null, "Reserved for local use", null),
		qmb (null, null, "Reserved for local use", null),
		qmc (null, null, "Reserved for local use", null),
		qmd (null, null, "Reserved for local use", null),
		qme (null, null, "Reserved for local use", null),
		qmf (null, null, "Reserved for local use", null),
		qmg (null, null, "Reserved for local use", null),
		qmh (null, null, "Reserved for local use", null),
		qmi (null, null, "Reserved for local use", null),
		qmj (null, null, "Reserved for local use", null),
		qmk (null, null, "Reserved for local use", null),
		qml (null, null, "Reserved for local use", null),
		qmm (null, null, "Reserved for local use", null),
		qmn (null, null, "Reserved for local use", null),
		qmo (null, null, "Reserved for local use", null),
		qmp (null, null, "Reserved for local use", null),
		qmq (null, null, "Reserved for local use", null),
		qmr (null, null, "Reserved for local use", null),
		qms (null, null, "Reserved for local use", null),
		qmt (null, null, "Reserved for local use", null),
		qmu (null, null, "Reserved for local use", null),
		qmv (null, null, "Reserved for local use", null),
		qmw (null, null, "Reserved for local use", null),
		qmx (null, null, "Reserved for local use", null),
		qmy (null, null, "Reserved for local use", null),
		qmz (null, null, "Reserved for local use", null),
		qna (null, null, "Reserved for local use", null),
		qnb (null, null, "Reserved for local use", null),
		qnc (null, null, "Reserved for local use", null),
		qnd (null, null, "Reserved for local use", null),
		qne (null, null, "Reserved for local use", null),
		qnf (null, null, "Reserved for local use", null),
		qng (null, null, "Reserved for local use", null),
		qnh (null, null, "Reserved for local use", null),
		qni (null, null, "Reserved for local use", null),
		qnj (null, null, "Reserved for local use", null),
		qnk (null, null, "Reserved for local use", null),
		qnl (null, null, "Reserved for local use", null),
		qnm (null, null, "Reserved for local use", null),
		qnn (null, null, "Reserved for local use", null),
		qno (null, null, "Reserved for local use", null),
		qnp (null, null, "Reserved for local use", null),
		qnq (null, null, "Reserved for local use", null),
		qnr (null, null, "Reserved for local use", null),
		qns (null, null, "Reserved for local use", null),
		qnt (null, null, "Reserved for local use", null),
		qnu (null, null, "Reserved for local use", null),
		qnv (null, null, "Reserved for local use", null),
		qnw (null, null, "Reserved for local use", null),
		qnx (null, null, "Reserved for local use", null),
		qny (null, null, "Reserved for local use", null),
		qnz (null, null, "Reserved for local use", null),
		qoa (null, null, "Reserved for local use", null),
		qob (null, null, "Reserved for local use", null),
		qoc (null, null, "Reserved for local use", null),
		qod (null, null, "Reserved for local use", null),
		qoe (null, null, "Reserved for local use", null),
		qof (null, null, "Reserved for local use", null),
		qog (null, null, "Reserved for local use", null),
		qoh (null, null, "Reserved for local use", null),
		qoi (null, null, "Reserved for local use", null),
		qoj (null, null, "Reserved for local use", null),
		qok (null, null, "Reserved for local use", null),
		qol (null, null, "Reserved for local use", null),
		qom (null, null, "Reserved for local use", null),
		qon (null, null, "Reserved for local use", null),
		qoo (null, null, "Reserved for local use", null),
		qop (null, null, "Reserved for local use", null),
		qoq (null, null, "Reserved for local use", null),
		qor (null, null, "Reserved for local use", null),
		qos (null, null, "Reserved for local use", null),
		qot (null, null, "Reserved for local use", null),
		qou (null, null, "Reserved for local use", null),
		qov (null, null, "Reserved for local use", null),
		qow (null, null, "Reserved for local use", null),
		qox (null, null, "Reserved for local use", null),
		qoy (null, null, "Reserved for local use", null),
		qoz (null, null, "Reserved for local use", null),
		qpa (null, null, "Reserved for local use", null),
		qpb (null, null, "Reserved for local use", null),
		qpc (null, null, "Reserved for local use", null),
		qpd (null, null, "Reserved for local use", null),
		qpe (null, null, "Reserved for local use", null),
		qpf (null, null, "Reserved for local use", null),
		qpg (null, null, "Reserved for local use", null),
		qph (null, null, "Reserved for local use", null),
		qpi (null, null, "Reserved for local use", null),
		qpj (null, null, "Reserved for local use", null),
		qpk (null, null, "Reserved for local use", null),
		qpl (null, null, "Reserved for local use", null),
		qpm (null, null, "Reserved for local use", null),
		qpn (null, null, "Reserved for local use", null),
		qpo (null, null, "Reserved for local use", null),
		qpp (null, null, "Reserved for local use", null),
		qpq (null, null, "Reserved for local use", null),
		qpr (null, null, "Reserved for local use", null),
		qps (null, null, "Reserved for local use", null),
		qpt (null, null, "Reserved for local use", null),
		qpu (null, null, "Reserved for local use", null),
		qpv (null, null, "Reserved for local use", null),
		qpw (null, null, "Reserved for local use", null),
		qpx (null, null, "Reserved for local use", null),
		qpy (null, null, "Reserved for local use", null),
		qpz (null, null, "Reserved for local use", null),
		qqa (null, null, "Reserved for local use", null),
		qqb (null, null, "Reserved for local use", null),
		qqc (null, null, "Reserved for local use", null),
		qqd (null, null, "Reserved for local use", null),
		qqe (null, null, "Reserved for local use", null),
		qqf (null, null, "Reserved for local use", null),
		qqg (null, null, "Reserved for local use", null),
		qqh (null, null, "Reserved for local use", null),
		qqi (null, null, "Reserved for local use", null),
		qqj (null, null, "Reserved for local use", null),
		qqk (null, null, "Reserved for local use", null),
		qql (null, null, "Reserved for local use", null),
		qqm (null, null, "Reserved for local use", null),
		qqn (null, null, "Reserved for local use", null),
		qqo (null, null, "Reserved for local use", null),
		qqp (null, null, "Reserved for local use", null),
		qqq (null, null, "Reserved for local use", null),
		qqr (null, null, "Reserved for local use", null),
		qqs (null, null, "Reserved for local use", null),
		qqt (null, null, "Reserved for local use", null),
		qqu (null, null, "Reserved for local use", null),
		qqv (null, null, "Reserved for local use", null),
		qqw (null, null, "Reserved for local use", null),
		qqx (null, null, "Reserved for local use", null),
		qqy (null, null, "Reserved for local use", null),
		qqz (null, null, "Reserved for local use", null),
		qra (null, null, "Reserved for local use", null),
		qrb (null, null, "Reserved for local use", null),
		qrc (null, null, "Reserved for local use", null),
		qrd (null, null, "Reserved for local use", null),
		qre (null, null, "Reserved for local use", null),
		qrf (null, null, "Reserved for local use", null),
		qrg (null, null, "Reserved for local use", null),
		qrh (null, null, "Reserved for local use", null),
		qri (null, null, "Reserved for local use", null),
		qrj (null, null, "Reserved for local use", null),
		qrk (null, null, "Reserved for local use", null),
		qrl (null, null, "Reserved for local use", null),
		qrm (null, null, "Reserved for local use", null),
		qrn (null, null, "Reserved for local use", null),
		qro (null, null, "Reserved for local use", null),
		qrp (null, null, "Reserved for local use", null),
		qrq (null, null, "Reserved for local use", null),
		qrr (null, null, "Reserved for local use", null),
		qrs (null, null, "Reserved for local use", null),
		qrt (null, null, "Reserved for local use", null),
		qru (null, null, "Reserved for local use", null),
		qrv (null, null, "Reserved for local use", null),
		qrw (null, null, "Reserved for local use", null),
		qrx (null, null, "Reserved for local use", null),
		qry (null, null, "Reserved for local use", null),
		qrz (null, null, "Reserved for local use", null),
		qsa (null, null, "Reserved for local use", null),
		qsb (null, null, "Reserved for local use", null),
		qsc (null, null, "Reserved for local use", null),
		qsd (null, null, "Reserved for local use", null),
		qse (null, null, "Reserved for local use", null),
		qsf (null, null, "Reserved for local use", null),
		qsg (null, null, "Reserved for local use", null),
		qsh (null, null, "Reserved for local use", null),
		qsi (null, null, "Reserved for local use", null),
		qsj (null, null, "Reserved for local use", null),
		qsk (null, null, "Reserved for local use", null),
		qsl (null, null, "Reserved for local use", null),
		qsm (null, null, "Reserved for local use", null),
		qsn (null, null, "Reserved for local use", null),
		qso (null, null, "Reserved for local use", null),
		qsp (null, null, "Reserved for local use", null),
		qsq (null, null, "Reserved for local use", null),
		qsr (null, null, "Reserved for local use", null),
		qss (null, null, "Reserved for local use", null),
		qst (null, null, "Reserved for local use", null),
		qsu (null, null, "Reserved for local use", null),
		qsv (null, null, "Reserved for local use", null),
		qsw (null, null, "Reserved for local use", null),
		qsx (null, null, "Reserved for local use", null),
		qsy (null, null, "Reserved for local use", null),
		qsz (null, null, "Reserved for local use", null),
		qta (null, null, "Reserved for local use", null),
		qtb (null, null, "Reserved for local use", null),
		qtc (null, null, "Reserved for local use", null),
		qtd (null, null, "Reserved for local use", null),
		qte (null, null, "Reserved for local use", null),
		qtf (null, null, "Reserved for local use", null),
		qtg (null, null, "Reserved for local use", null),
		qth (null, null, "Reserved for local use", null),
		qti (null, null, "Reserved for local use", null),
		qtj (null, null, "Reserved for local use", null),
		qtk (null, null, "Reserved for local use", null),
		qtl (null, null, "Reserved for local use", null),
		qtm (null, null, "Reserved for local use", null),
		qtn (null, null, "Reserved for local use", null),
		qto (null, null, "Reserved for local use", null),
		qtp (null, null, "Reserved for local use", null),
		qtq (null, null, "Reserved for local use", null),
		qtr (null, null, "Reserved for local use", null),
		qts (null, null, "Reserved for local use", null),
		qtt (null, null, "Reserved for local use", null),
		qtu (null, null, "Reserved for local use", null),
		qtv (null, null, "Reserved for local use", null),
		qtw (null, null, "Reserved for local use", null),
		qtx (null, null, "Reserved for local use", null),
		qty (null, null, "Reserved for local use", null),
		qtz (null, null, "Reserved for local use", null),

		que ("qu", "Runa Simi, Kichwa", "Quechua", null),

		raj (null, "राजस�?थानी", "	Rajasthani", "\u0930\u093e\u091c\u0938\u094d\u0925\u093e\u0928\u0940"),
		rap (null, "Rapanui, pepito ote henua", "Rapanui", null),
		rar (null, "Rarotongan", "Cook Islands Maori", null),
		rcf ("rc", "Kréol rénioné", "Reunionese, Reunion Creole", null),
		roa (null, null, "Romance languages", null),
		roh ("rm", "Rumantsch grischun", "Romansh", null),
		rom (null, "Romani ćhib, Romani šib, Romanó", "Romany", "\u0052\u006f\u006d\u0061\u006e\u0069 \u0107\u0068\u0069\u0062\u002c \u0052\u006f\u006d\u0061\u006e\u0069 \u0161\u0069\u0062\u002c \u0052\u006f\u006d\u0061\u006e\u00f3"),
		ron ("ro", "română", "Romanian, Moldavian, Moldovan", "\u0072\u006f\u006d\u00e2\u006e\u0103"),
		rum ("ro", "română", "Romanian, Moldavian, Moldovan", "\u0072\u006f\u006d\u00e2\u006e\u0103"),
		run ("rn", "kiRundi", "Rundi", null),
		rup (null, "Armãneashce, Armãneashti, Limba armãneascã", "Aromanian, Arumanian, Macedo-Romanian", "\u0041\u0072\u006d\u00e3\u006e\u0065\u0061\u0073\u0068\u0063\u0065\u002c \u0041\u0072\u006d\u00e3\u006e\u0065\u0061\u0073\u0068\u0074\u0069\u002c \u004c\u0069\u006d\u0062\u0061 \u0061\u0072\u006d\u00e3\u006e\u0065\u0061\u0073\u0063\u00e3"),
		rus ("ru", "ру�?�?кий �?зык", "Russian", "\u0440\u0443\u0441\u0441\u043a\u0438\u0439 \u044f\u0437\u044b\u043a"),

		sad (null, "Sandawé", "Sandawe", null),
		sag ("sg", "Yângâ tî sängö", "Sango", null),
		sah (null, "Саха тыла", "Yakut", "\u0421\u0430\u0445\u0430 \u0442\u044b\u043b\u0430"),
		sai (null, null, "South American Indian languages", null),
		sal (null, null, "Salishan languages", null),
		sam (null, "�?רמית, �?ܪܡ�?�?", "Samaritan Aramaic", "\u05d0\u05e8\u05de\u05d9\u05ea\u002c \u0710\u072a\u0721\u071d\u0710"),
		san ("sa", "संस�?कृतम�?", "Sanskrit", "\u0938\u0902\u0938\u094d\u0915\u0943\u0924\u092e\u094d"),
		sas (null, "Sasak", "Sasak", null),
		sat (null, "संथाली ", "Santali", "\u0938\u0902\u0925\u093e\u0932\u0940"),
		scc ("sr", "�?рп�?ки", "Serbian", "\u0441\u0440\u043f\u0441\u043a\u0438"),
		scn (null, "Sicilianu", "Sicilian", null),
		sco (null, "Scoats leid, Lallans", "Scots", null),
		scr ("hr", "hrvatski", "Croatian", ""),
		sel (null, "шӧльӄумыт әты", "Selkup", "\u0448\u04e7\u043b\u044c\u04c4\u0443\u043c\u044b\u0442 \u04d9\u0442\u044b"),
		sem (null, null, "Semitic languages", null),
		sga (null, "Goídelc", "Old Irish  (to 900)", null),
		sgn (null, null, "Sign languages", null),
		shn (null, "Shan", "Shan", null),
		shp (null, "Shipibo-conibo", "Shipibo language", null),
		sid (null, "Sidámo 'Afó", "Sidamo", null),
		sin ("si", "සිංහල", "Sinhalese, Sinhala", "\u0dc3\u0dd2\u0d82\u0dc4\u0dbd"),
		sio (null, null, "Siouan languages", null),
		sit (null, null, "Sino-Tibetan languages", null),
		sla (null, null, "Slavic languages", null),
		slk ("sk", "Sloven�?ina", "Slovak", "\u0053\u006c\u006f\u0076\u0065\u006e\u010d\u0069\u006e\u0061"),
		slo ("sk", "Sloven�?ina", "Slovak", "\u0053\u006c\u006f\u0076\u0065\u006e\u010d\u0069\u006e\u0061"),
		slv ("sl", "Slovenš�?ina", "Slovenian", "\u0053\u006c\u006f\u0076\u0065\u006e\u0161\u010d\u0069\u006e\u0061"),
		sma (null, "Saemien giele", "Southern Sami", null),
		sme ("se", "Sámi, sámegiella", "Northern Sami", null),
		smi (null, null, "Sami languages", null),
		smj (null, "Sámegiella", "Lule Sami", null),
		smn (null, "Säämegiella", "Inari Sami", null),
		smo ("sm", "gagana fa'a Samoa", "Samoan", null),
		sms (null, "sääʼmǩiõll", "Skolt Sami", "\u0073\u00e4\u00e4\u02bc\u006d\u01e9\u0069\u00f5\u006c\u006c"),
		sna ("sn", "chiShona", "Shona", null),
		snd ("sd", "سنڌي، سندھی, सिन�?धी ", "Sindhi", "\u0633\u0646\u068c\u064a\u060c \u0633\u0646\u062f\u06be\u06cc\u002c \u0938\u093f\u0928\u094d\u0927\u0940"),
		snk (null, "Soninkanxaane", "Soninke", null),
		sog (null, "Sogdien", "Sogdian", null),
		som ("so", "Soomaaliga, af Soomaali", "Somali", null),
		son (null, null, "Songhai languages", null),
		sot ("st", "seSotho", "Southern Sotho", null),
		spa ("es", "Español, castellano", "Spanish, Castilian", null),
		sqi ("sq", "Shqip", "Albanian", ""),
		srd ("sc", "Sardu", "Sardinian", null),
		srn (null, "Sranan tongo", "Sranan Tongo", null),
		srp ("sr", "�?рп�?ки", "Serbian", "\u0441\u0440\u043f\u0441\u043a\u0438"),
		srr (null, "Sérère", "Serer", null),
		ssa (null, null, "Nilo-Saharan languages", null),
		ssw ("ss", "siSwati", "Swati", null),
		suk (null, "Sukuma", "Sukuma", null),
		sun ("su", "basa Sunda", "Sundanese", null),
		sus (null, "Soussou", "Susu", null),
		sux (null, "eme-�?ir", "Sumerian", "\u0065\u006d\u0065\u002d\u011d\u0069\u0072"),
		swa ("sw", "Kiswahili", "Swahili", null),
		swe ("sv", "Svenska", "Swedish", null),
		syc (null, null, "Classical Syriac", null),
		syr (null, "ܣܘܪ�?�?�?", "Syriac", "\u0723\u0718\u072a\u071d\u071d\u0710"),

		tah ("ty", "te reo Tahiti, te reo M�?ʼohi", "Tahitian", null),
		tai (null, null, "Tai languages", null),
		tam ("ta", "தமிழ�?", "Tamil", "\u0ba4\u0bae\u0bbf\u0bb4\u0bcd"),
		tat ("tt", "татарча, tatarça, تاتارچا", "	Tatar", "\u0442\u0430\u0442\u0430\u0440\u0447\u0430\u002c \u0074\u0061\u0074\u0061\u0072\u00e7\u0061\u002c \u062a\u0627\u062a\u0627\u0631\u0686\u0627"),
		tel ("te", "తెల�?గ�?", "Telugu", "\u0c24\u0c46\u0c32\u0c41\u0c17\u0c41"),
		tem (null, "Timné", "Timne", null),
		ter (null, "Téréno", "Tereno", null),
		tet (null, "Tetun", "Tetum", null),
		tgk ("tg", "тоҷикӣ, تاجیکی", "Tajik", "\u0442\u043e\u04b7\u0438\u043a\u04e3\u002c \u062a\u0627\u062c\u06cc\u06a9\u06cc"),
		tgl ("tl", "Tagalog", "Tagalog", null),
		tha ("th", "ภาษาไทย", "Thai", "\u0e20\u0e32\u0e29\u0e32\u0e44\u0e17\u0e22"),
		tib ("bo", "བོད་ཡིག", "Tibetan", "\u0f56\u0f7c\u0f51\u0f0b\u0f61\u0f72\u0f42"),
		tig (null, "Tigré, Khasa", "Tigre", null),
		tir ("ti", "ት�?ርኛ", "Tigrinya", "\u1275\u130d\u122d\u129b"),
		tiv (null, "Tiv", "Tiv", null),
		tkl (null, "Tokelau", "Tokelau", null),
		tlh (null, "tlhIngan Hol", "Klingon", null),
		tli (null, "Lingít", "Tlingit", null),
		tmh (null, "Tamajeq, ɫ[ǂ…", "Tamashek", "\u0054\u0061\u006d\u0061\u006a\u0065\u0071\u002c \u026b\u005b\u01c2\u2026"),
		tog (null, "chiTonga", "Tonga  (Nyasa)", null),
		ton ("to", "faka-Tonga", "Tongan  (Tonga Islands)", null),
		tpi (null, "Tok Pisin", "Tok Pisin", null),
		tsi (null, "Tsimchiane", "Tsimshian", null),
		tsn ("tn", "seTswana", "Tswana", null),
		tso ("ts", "xiTsonga", "Tsonga", null),
		tuk ("tk", "Түркмен", "Turkmen", "\u0422\u04af\u0440\u043a\u043c\u0435\u043d"),
		tum (null, "chiTumbuka", "Tumbuka", null),
		tup (null, "Nheengatu", "Tupi languages", null),
		tur ("tr", "Türkçe", "Turkish", null),
		tut (null, null, "Altaic languages", null),
		tvl (null, "'gana Tuvalu", "Tuvalu", null),
		twi ("tw", "Tchi", "Twi", null),
		tyv (null, "тыва дыл", "Tuvinian", "\u0442\u044b\u0432\u0430 \u0434\u044b\u043b"),

		udm (null, "удмурт кыл", "Udmurt", "\u0443\u0434\u043c\u0443\u0440\u0442 \u043a\u044b\u043b"),
		uga (null, null, "Ugaritic", null),
		uig ("ug", "Uyƣurqə, Uyğurçe, ئۇيغۇرچ", "Uighur, Uyghur", "\u0055\u0079\u01a3\u0075\u0072\u0071\u0259\u002c \u0055\u0079\u011f\u0075\u0072\u00e7\u0065\u002c \u0626\u06c7\u064a\u063a\u06c7\u0631\u0686"),
		ukr ("uk", "україн�?ька мова", "Ukrainian", "\u0443\u043a\u0440\u0430\u0457\u043d\u0441\u044c\u043a\u0430 \u043c\u043e\u0432\u0430\u0626\u06c7\u064a\u063a\u06c7\u0631\u0686"),
		umb (null, "Umbúndú", "Umbundu", null),
		und (null, null, "Undetermined language", null),
		urd ("ur", "اردو", "Urdu", "\u0627\u0631\u062f\u0648"),
		uzb ("uz", "O'zbek, Ўзбек, أۇزب�?ك", "Uzbek", "\u004f\u0027\u007a\u0062\u0065\u006b\u002c \u040e\u0437\u0431\u0435\u043a\u002c \u0623\u06c7\u0632\u0628\u06d0\u0643"),

		vai (null, "Vaï", "Vai", null),
		ven ("ve", "tshiVenḓa", "Venda", null),
		vie ("vi", "Tiếng Việt", "Vietnamese", "\u0054\u0069\u1ebf\u006e\u0067 \u0056\u0069\u1ec7\u0074"),
		vo ("vo", "Volapük", "Volapük", null),
		vot (null, "Va�?�?a tšeeli", "Votic", "\u0056\u0061\u010f\u010f\u0061 \u0074\u0161\u0065\u0065\u006c\u0069"),

		wak (null, null, "Wakashan languages", null),
		wal (null, "Wolaitta, wolaytta", "Wolaitta, Wolaytta", null),
		war (null, "Winaray, Lineyte-Samarnon", "Waray", null),
		was (null, "Washo", "Washo", null),
		wel ("cy", "Cymraeg", "Welsh", null),
		wen (null, null, "Sorbian languages", null),
		wln ("wa", "Walon", "Walloon", null),
		wol ("wo", "Wolof", "Wolof", null),

		xal (null, "хальмг келн", "Kalmyk, Oirat", "\u0445\u0430\u043b\u044c\u043c\u0433 \u043a\u0435\u043b\u043d"),
		xho ("xh", "isiXhosa", "Xhosa", null),

		yao (null, "Yao", "Yao", null),
		yap (null, "Yapois", "Yapese", null),
		yid ("yi", "ייִדיש", "Yiddish", "\u05d9\u05d9\u05b4\u05d3\u05d9\u05e9"),
		yor ("yo", "Yorùbá", "Yoruba", null),
		ypk (null, null, "Yupik languages", null),

		zap (null, "Zapotèque", "Zapotec", null),
		zbl (null, null, "Blissymbols, Blissymbolics, Bliss", null),
		zen (null, "Tu�?�?ungiyya", "Zenaga", "\u0054\u0075\u1e0d\u1e0d\u0075\u006e\u0067\u0069\u0079\u0079\u0061"),
		zgh (null, "Amazighe", "Standard Moroccan Tamazight", null),
		zha ("za", "Saɯ cueŋƅ, Saw cuengh", "Zhuang, Chuang", "\u0053\u0061\u026f \u0063\u0075\u0065\u014b\u0185\u002c \u0053\u0061\u0077 \u0063\u0075\u0065\u006e\u0067\u0068"),
		zho ("zh", "中文", "Chinese", "\u4e2d\u6587"), // Chinese chars do not render
		znd (null, null, "Zande languages", null),
		zul ("zu", "isiZulu", "Zulu", null),
		zun (null, "Shiwi", "Zuni", null),
		zxx (null, null, "No linguistic content, not applicable", null),
		zza (null, "Zaza, dimili, dimli, kirdki, kirmanjki, zazaki", "Zaza, Dimili, Dimli, Kirdki, Kirmanjki, Zazaki", null);
	
		/** The iso 639 alpha-2 code for this language */
		private String isoCodeAlpha2;
		/** The language name in English */
		private String languageName;
		/** The original (native) language name */
		private String originalLanguageName;
		/** The unicode UTF-16BE representation of the original Language Name if not in the Latin CharSet */
        private String unicode;
         
        /** 
         * Constructs a new ISO 639 language enumeration value.
         * <p>
         * @param isoCodeAlpha2 the alpha-2 code or null if none
         * @param originalLanguageName the local name or null if generic language code
         * @param languageName the English name
         * @param unicode the UTF-16BE representation of <code>originaLanguageName</code> or null if default applies, e.g. programmatically done using <code>originalLanguageName</code>
         */
		private Iso639LanguageCode (String isoCodeAlpha2, String originalLanguageName, String languageName, String unicode) {
			this.isoCodeAlpha2 = isoCodeAlpha2;
			this.languageName = languageName;
			this.originalLanguageName = originalLanguageName;
			this.unicode = unicode;
		}

		/** Returns the alpha-3 code for this language; special handling for [newb] code, as "new" is a java reserved word. */
		public String getIsoCodeAlpha3() {
			if (this == newb) return "new"; // caters for reserved java word 'new' 
			else return this.name(); 
		}
		
		/** Gets the alpha-2 code for this language, or null if none. */
		public String getIsoCodeAlpha2() { return isoCodeAlpha2; }
		
		/** Gets the English name for this language */
		public String getLanguageName() { return languageName; }

		/**
		 * Gets the original language name.
		 * <p>
		 * If <code>originalLanguageName</code> is null and <code>unicode</code> is not null, then <code>unicode</code> is returned:
		 * If both <code>unicode</code> and <code>originalLanguageName</code> are null, it returns <code>languageName</code>
		 */
		public String getOriginalLanguageName() { 
			if (originalLanguageName != null) return originalLanguageName;
			else if (unicode != null) return unicode;
			else return languageName;
		}
		
		/** 
		 * Gets the UTF-16BE String representation for this (original) language name. 
		 * <p>
		 * If <code>unicode</code> is null and <code>originalLanguageName</code> is not null, then the unicode is created from <code>originalLanguageName</code>;
		 * If both <code>unicode</code> and <code>originalLanguageName</code> are null, \u003F ('?') is returned.
		 * */
		public String getUnicode() {
			String utf16;
			StringBuffer buf = new StringBuffer();
			if (unicode == null) {
				if (originalLanguageName != null) {
					for (int i=0; i<originalLanguageName.length(); i++) {
						buf.append(String.format ("\\u%04x", (int)originalLanguageName.charAt(i)));
					}
					utf16 = buf.toString();
				} else utf16 = "\u003F"; // "?"
			} else utf16 = unicode;
			return utf16; 
		}
		
		/** Returns a Human readable representation of this Language Code. */
		@Override public String toString() {
			StringBuffer buf = new StringBuffer();
			buf.append(languageName);
			buf.append(" (" + getIsoCodeAlpha3() + ", " + (isoCodeAlpha2 == null? "no Alpha-2 code" : getIsoCodeAlpha2()) + ")");
			if (originalLanguageName != null) buf.append(", original language name(s): " + originalLanguageName);
			return buf.toString();
		}
		
	}
	
	/** 
	 * The list of ISO 639-1 language codes (Alpha-2 code).
	 * <p>
	 * This list is less complete than ISO 639-2, thus kept very simple; it should be considered as a shorthand to Iso639LanguageCode.
	 */
	public enum Iso639Alpha2LanguageCode {
		
		aa("aar"),
		ab("abk"),
		ae("ave"),
		af("afr"),
		ak("aka"),
		am("amh"),
		an("arg"),
		ar("ara"),
		as("asm"),
		av("ava"),
		ay("aym"),
		az("aze"),
		ba("bak"),
		be("bel"),
		bg("bul"),
		bh("bih"),
		bi("bis"),
		bm("bam"),
		bn("ben"),
		bo("tib"),
		br("bre"),
		bs("bos"),
		ca("cat"),
		ce("che"),
		ch("cha"),
		co("cos"),
		cr("cre"),
		cs("cze"),
		cu("chu"),
		cv("chv"),
		cy("wel"),
		da("dan"),
		de("deu"),
		dv("div"),
		dz("dzo"),
		ee("ewe"),
		el("ell"),
		en("eng"),
		eo("epo"),
		es("spa"),
		et("est"),
		eu("eus"),
		fa("fas"),
		ff("ful"),
		fi("fin"),
		fj("fij"),
		fo("fao"),
		fr("fra"),
		fy("fry"),
		ga("gle"),
		gd("gla"),
		gl("glg"),
		gn("grn"),
		gu("guj"),
		gv("glv"),
		ha("hau"),
		he("heb"),
		hi("hin"),
		ho("hmo"),
		hr("hrv"),
		ht("hat"),
		hu("hun"),
		hy("hye"),
		hz("her"),
		ia("ina"),
		id("ind"),
		ie("ile"),
		ig("ibo"),
		ii("iii"),
		ik("ipk"),
		io("ido"),
		is("isl"),
		it("ita"),
		iu("iku"),
		ja("jpn"),
		jv("jav"),	
		ka("kat"),
		kg("kon"),
		ki("kik"),
		kj("kua"),
		kk("kaz"),
		kl("kal"),
		km("khm"),
		kn("kan"),
		ko("kor"),
		kr("kau"),
		ks("kas"),
		ku("kur"),
		kv("kom"),
		kw("cor"),
		ky("kir"),
		la("lat"),
		lb("ltz"),
		lg("lug"),
		li("lim"),
		ln("lin"),
		lo("lao"),
		lt("lit"),
		lu("lub"),
		lv("lav"),
		mg("mlg"),
		mh("mah"),
		mi("mri"),
		mk("mkd"),
		ml("mal"),
		mn("mon"),
		mo("mol"),
		mr("mar"),
		ms("msa"),
		mt("mlt"),
		my("mya"),
		na("nau"),
		nb("nob"),
		nd("nde"),
		ne("nep"),
		ng("ndo"),
		nl("nld"),
		nn("nno"),
		no("nor"),
		nr("nbl"),
		nv("nav"),
		ny("nya"),
		oc("oci"),
		oj("oji"),
		om("orm"),
		or("ori"),
		os("oss"),
		pa("pan"),
		pi("pli"),
		pl("pol"),
		ps("pus"),
		pt("por"),
		qu("que"),
		rc("rcf"),
		rm("roh"),
		rn("run"),
		ro("ron"),
		ru("rus"),
		rw("kin"),
		sa("san"),
		sc("srd"),
		sd("snd"),
		se("sme"),
		sg("sag"),
		sh("sla"),
		si("sin"),
		sk("slk"),
		sl("slv"),
		sm("smo"),
		sn("sna"),
		so("som"),
		sq("sqi"),
		sr("srp"),
		ss("ssw"),
		st("sot"),
		su("sun"),
		sv("swe"),
		sw("swa"),
		ta("tam"),
		te("tel"),
		tg("tgk"),
		th("tha"),
		ti("tir"),
		tk("tuk"),
		tl("tgl"),
		tn("tsn"),
		to("ton"),
		tr("tur"),
		ts("tso"),
		tt("tat"),
		tw("twi"),
		ty("tah"),
		ug("uig"),
		uk("ukr"),
		ur("urd"),
		uz("uzb"),
		ve("ven"),
		vi("vie"),
		vo("vol"),
		wa("wln"),
		wo("wol"),
		xh("xho"),
		yi("yid"),
		yo("yor"),
		za("zha"),	
		zh("zho"),
		zu("zul");

		/** The underlying full enumeration. */
		private Iso639LanguageCode languageCode;
		
		/** 
		 * Builds a new enumeration value and instantiates the underlying Iso639 Alpha-3 Language code enumeration.
		 * @param alpha3Code the language alpha-3 code as String needed to obtain the {@link #Iso639LanguageCode} instance
		 * @throws IllegalArgumentException if <code>alpha3Code</code> is not a valid code
		 */
		private Iso639Alpha2LanguageCode (String alpha3Code) throws IllegalArgumentException {
			this.languageCode = Iso639LanguageCode.valueOf(alpha3Code);
		}
		
		/** Simply returns the enum value as String. */
		public String getAlpha2Code() { return this.name(); }
		
		/** Returns the alpha-3 code for this language code. */
		public String getAlpha3Code() { return languageCode.getIsoCodeAlpha3(); }
		
		/** Returns the English language name for this language code. */
		public String getLanguageName() { return languageCode.getLanguageName(); }
		
		/** Returns the original language name for this language code. */
		public String getOriginalLanguageName() { return languageCode.getOriginalLanguageName(); }

		/** Returns the unicode UFT16-BE representation of the (original) language code, for instance if the CharSet does not render. */
		public String getUnicode() { return languageCode.getUnicode(); }
		
	}
	
}
